name: v1
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x

      - name: npm packages install
        run: npm install

      - name: Deploy
        run: npm run deploy
